# Generated by Django 6.0.5 on 2026-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.CharField(blank=True, help_text='Auto-generated plain-text password. Cleared after user changes it.', max_length=128, null=True),
        ),
    ]
