# Generated by Django 6.0.5 on 2026-07-14 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_gradescale_term_exam_assessment_marksentry_and_more'),
        ('students', '0003_rename_roll_number_student_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Academics.academicyear'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Academics.level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Academics.schoolclass'),
            preserve_default=False,
        ),
    ]
