# Generated by Django 6.0.5 on 2026-06-13 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('qualification', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('others', 'Others')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('teaching_level', models.CharField(choices=[('primary', 'Primary (1–5)'), ('lower_secondary', 'Lower Secondary (6–8)'), ('secondary', 'Secondary (9–10)'), ('plus2', '+2 College (11–12)'), ('all', 'All Levels')], default='secondary', max_length=30)),
                ('faculty', models.CharField(blank=True, help_text='Only for +2 (Science / Management / Arts)', max_length=100, null=True)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('day', 'Day'), ('both', 'Both')], default='day', max_length=10)),
                ('joining_date', models.DateField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resigned', 'Resigned'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
